version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ddnetone-frontend:latest
    container_name: ddnet-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ddnetone-backend:latest
    container_name: ddnet-backend
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
    environment:
      GIN_MODE: release
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: ddnet-db
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  db_data:
